apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secrets
type: Opaque
stringData:
  username: petclinic
  password: petclinic # Puedes cambiarla, pero recuerda actualizar el Jenkinsfile luego