apiVersion: v1
kind: Secret
metadata:
  name: gitea-test-cicd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  # Debe ser EXACTAMENTE la misma URL que tienes en tu Application
  url: 'http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/test-cicd-maven-2.git'
  # Reemplaza con tus credenciales reales de Gitea
  username: "gitea_admin" 
  password: "mipasswordseguro"